sudo: false
dist: trusty

language: node_js
node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - if [ -f $(git rev-parse --git-dir)/shallow ]; then git fetch --unshallow; fi
  - yarn

script:
  - yarn build
  - yarn build-zip
  - test -f dist/manifest.json
  - test -f dist/background.js
  - test -f dist/vendor.js
  - cmp src/icons/icon_48.png dist/icons/icon_48.png
  - cmp src/icons/icon_128.png dist/icons/icon_128.png
  - test -f "dist-zip/alderiate-live-v$(node -pe "require('./package.json').version").zip"

before_deploy:
  - export RELEASE_EXTENSION_FILE=$(ls dist-zip/*.zip)
  - echo "Deploying ${RELEASE_EXTENSION_FILE} to GitHub releases"

deploy:
  provider: releases
  api_key:
    secure: OclgPSp/EeIrkNDM1yZqgLQbRonT7dxSefKfpEYI2Efm8eMP0mny5tPItblT4xf5tvMTWUVwhP8ujk2i9YCXxeIXXpDWpJJIHBWT7LysjgdLfi2iLklKNorT9Sbus+bIevrVxKs+Neulp/9iiFfJtYg0Lj6C+Kz8TpRTyqRlwpVoeTnAen1rIFmtE1qyjN1h3qqLOXJ2xJjPNTWq+3Zd9vCyKhN2mimEa9PowlcB4m5rPDEFtgkqFaneCm+qSGOIjWf3xdfLasyAbu60ATlgn1y972N1eWqdpujO5u4I2BotuvsrM6Swaxsnf3epL5P4paFehQ2EbI30tsjTLmy/bFHwydBFhPNfiYbydAPjYeh5kUoALNMEbrfvN/y9sRBQb+nipIz6t3oz3WGKt8AcBi87Hog/Yy2aeuRdmKjBVPOmhHZTCv9+7mfzEPBYTqOQ0kiwt2P/ZmSlJW0O6BRlBlKTqoS8mrjWRymXTnUXWDiX0L4aI0P4fNYHDBkvlTAaZbOxV1y6My5FBZdAtiG02rDcRDSYdFwkyUZ6J4RXDlVxlFljR5O5KsuHywAnTLHn5h42GOoyb4ofgcAOy8sSULixewAOO1Jh3AAU//+mAQkO6+TiTupoz95DfWABAk5US26ZPolodsqQ6vc7QpQ+5VlmEcweWPHqI+vemghJiE0=
  file: "${RELEASE_EXTENSION_FILE}"
  skip_cleanup: true
  on:
    repo: Kocal/Alderiate-Live
    tags: true
